### ISSUE TITLE
[less] note avis

### ISSUE THREAD

**Issue by Shadownest** [philippe-3wa/avelo#6]
http://192.168.1.22/avelo/index.php?page=produit&id=31
j'ai supprimé la note par défaut avec le bouton "-" et en validant ça fait ça :
![Image](http://image.prntscr.com/image/33b8fece4dc447b08fe5f5b1715b962f.png)
(On peut remodifier la note précédente)

**Comment by philippe-3wa** [comment]
corrigé (on ne peut plus mettre de note à 0)
