### ISSUE TITLE
[less] panier vide mais payant

### ISSUE THREAD

**Issue by Shadownest** [philippe-3wa/avelo#7]
http://192.168.1.22/avelo/index.php?page=panier
J'ai ajouté un nombre négatif de produit à mon panier, du coup y'a pas de produit dedans, mais j'ai quand même un prix ?
![Image](http://image.prntscr.com/image/747557b87a534f7e9002b24b2cc48903.png)

**Comment by philippe-3wa** [comment]
corrigé
