### ISSUE TITLE
less réinscription impossible

### ISSUE THREAD

**Issue by gmarbach** [philippe-3wa/avelo#8]
Si on crée un compte utilisateur et qu'on le supprime, il n'est pas possible d'en recréer un avec les mêmes données.
(Erreur interne).
Du coup, je suis triste.

**Comment by gmarbach** [comment]
NB: il semblerait que cela soit aussi le cas en n'utilisant qu'une partie des données déjà utilisées:
Par exemple, si je change de nom et prénom, mais que je reprends la même adresse mail, cela indique la même erreur.

**Comment by philippe-3wa** [comment]
en fait quand on supprime son compte on ne fait que le désactiver, pas le supprimer.
et dans la base de données les champs email et login sont uniques pour plus de sécurité.
